(function()
{
	createNamespace("TF.GIS").Resources = Resources;

	function Resources() { }

	/**
	 * Load ArcGIS Maps SDK for JavaScript
	 * @returns
	 */
	Resources.Load = async () =>
	{
		Resources.loadingPromise = Resources.loadingPromise ||
			new Promise((resolve) =>
			{
				require({}, [
					"esri/Map",
					"esri/Basemap",
					"esri/views/MapView",
					"esri/layers/GraphicsLayer",
					"esri/layers/MapImageLayer",
					"esri/Graphic",
					"esri/geometry/SpatialReference",
					"esri/layers/FeatureLayer",
					"esri/request",
					"esri/config",
					"esri/Color",
					"esri/symbols/Font",
					"esri/symbols/PictureMarkerSymbol",
					"esri/symbols/SimpleFillSymbol",
					"esri/symbols/SimpleLineSymbol",
					"esri/symbols/SimpleMarkerSymbol",
					"esri/symbols/TextSymbol",
					"esri/widgets/BasemapGallery",
					"esri/widgets/Directions",
					"esri/widgets/Search",
					"esri/geometry/Extent",
					"esri/geometry/Point",
					"esri/geometry/Polygon",
					"esri/geometry/Circle",
					"esri/geometry/Polyline",
					"esri/geometry/Multipoint",
					"esri/geometry/support/webMercatorUtils",
					"esri/views/draw/Draw",
					"esri/rest/geoprocessor",
					"esri/rest/support/FeatureSet",
					"esri/rest/support/DirectionsFeatureSet",
					"esri/rest/support/ServiceAreaParameters",
					"esri/rest/locator",
					"esri/rest/support/ProjectParameters",
					"esri/core/reactiveUtils",
					"esri/rest/support/Query",
					"esri/geometry/Geometry",
					"esri/geometry/geometryEngine",
					"esri/widgets/Sketch/SketchViewModel",
					"esri/identity/IdentityManager",
					"esri/rest/support/RouteParameters",
					"esri/layers/TileLayer",
					"esri/layers/VectorTileLayer",
					"esri/widgets/Popup",
					"esri/PopupTemplate",
					"esri/layers/support/TileInfo",
					"esri/views/draw/support/settings",
					"esri/geometry/support/geodesicUtils"
				], function(
					EsriMap,
					Basemap,
					MapView,
					GraphicsLayer,
					MapImageLayer,
					Graphic,
					SpatialReference,
					FeatureLayer,
					esriRequest,
					esriConfig,
					Color,
					Font,
					PictureMarkerSymbol,
					SimpleFillSymbol,
					SimpleLineSymbol,
					SimpleMarkerSymbol,
					TextSymbol,
					BasemapGallery,
					Directions,
					Search,
					Extent,
					Point,
					Polygon,
					Circle,
					Polyline,
					Multipoint,
					webMercatorUtils,
					Draw,
					Geoprocessor,
					FeatureSet,
					DirectionsFeatureSet,
					ServiceAreaParameters,
					Locator,
					ProjectParameters,
					reactiveUtils,
					Query,
					Geometry,
					geometryEngine,
					SketchViewModel,
					IdentityManager,
					RouteParameters,
					TileLayer,
					VectorTileLayer,
					Popup,
					PopupTemplate,
					TileInfo,
					settings,
					geodesicUtils
				)
				{
					createNamespace("TF.GIS").SDK = {
						Color: Color,
						Map: EsriMap,
						Basemap: Basemap,
						MapView: MapView,
						FeatureLayer: FeatureLayer,
						SimpleMarkerSymbol: SimpleMarkerSymbol,
						SimpleLineSymbol: SimpleLineSymbol,
						BasemapGallery: BasemapGallery,
						GraphicsLayer: GraphicsLayer,
						MapImageLayer: MapImageLayer,
						SpatialReference: SpatialReference,
						Graphic: Graphic,
						Font: Font,
						PictureMarkerSymbol: PictureMarkerSymbol,
						SimpleFillSymbol: SimpleFillSymbol,
						TextSymbol: TextSymbol,
						Directions: Directions,
						Search: Search,
						Extent: Extent,
						Point: Point,
						Polygon: Polygon,
						Circle: Circle,
						Polyline: Polyline,
						Multipoint: Multipoint,
						webMercatorUtils: webMercatorUtils,
						Draw: Draw,
						Geoprocessor: Geoprocessor,
						FeatureSet: FeatureSet,
						DirectionsFeatureSet: DirectionsFeatureSet,
						ServiceAreaParameters: ServiceAreaParameters,
						Locator: Locator,
						ProjectParameters: ProjectParameters,
						reactiveUtils: reactiveUtils,
						Query: Query,
						Geometry: Geometry,
						geometryEngine: geometryEngine,
						SketchViewModel: SketchViewModel,
						RouteParameters: RouteParameters,
						esriRequest: esriRequest,
						esriConfig: esriConfig,
						TileLayer: TileLayer,
						VectorTileLayer: VectorTileLayer,
						IdentityManager: IdentityManager,
						Popup: Popup,
						PopupTemplate: PopupTemplate,
						TileInfo: TileInfo,
						settings: settings,
						geodesicUtils: geodesicUtils,
					};
					resolve();
				});
			});

		return Resources.loadingPromise;
	};
})();